services:
  weatherapi:
    image: weatherapi
    build:
      context: .
      dockerfile: ./DotNetApi/Dockerfile
    ports:
      - "5000:80"
    env_file:
      - ./DotNetApi/.env
  testtimer:
    image: testtimer
    build:
      context: .
      dockerfile: ./TestTimer/Dockerfile
    env_file:
      - ./TestTimer/.env